version: '3.8'

services:
  notification-action-history-service:
    container_name: connectfy-notification-action-history-service-dev
    image: connectfy/connectfy-notification-action-history-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
      - connectfy-kafka-network
      - connectfy-api-gateway-network
    environment:
      - NODE_ENV=development
      - PORT=7000
    #   - CHOKIDAR_USEPOLLING=true
    #   - CHOKIDAR_INTERVAL=1000
    #   - WATCHPACK_POLLING=true
    # command: npx nodemon --legacy-watch --watch src --ext ts,js,json --exec "npm run start:dev"
    env_file:
      - .env.development
    ports:
      - '7000:7000'

  mongo:
    image: mongo:6.0
    container_name: connectfy-notification-action-history-mongo-dev
    volumes:
      - mongo-data:/data/db
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notificationsDb
    ports:
      - '25201:27017'

volumes:
  mongo-data:

networks:
  connectfy-notification-action-history-network:
    external: true
  notifications-db-network:
  connectfy-kafka-network:
    external: true
  connectfy-api-gateway-network:
    external: true
