FROM node:20

WORKDIR /usr/src/app

# Force development install during image build
ENV NODE_ENV=development

COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

COPY . .

CMD ["npm", "run", "start:dev"]
