services:
  notification-action-history-service:
    image: connectfy/connectfy-notification-action-history-prod:1.0.0
    restart: always
    depends_on:
      - mongo
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
      - connectfy-api-gateway-network
      - connectfy-kafka-network
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/v1/health || exit 1"] # Bura dəyişməlidir
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: notificationsDb
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo-data:

networks:
  connectfy-notification-action-history-network:
    external: true
  notifications-db-network:
    driver: bridge
  connectfy-api-gateway-network:
    external: true
  connectfy-kafka-network:
    external: true