version: '3.8'

services:
  notification-action-history-service:
    container_name: connectfy-notification-action-history-service-prod
    image: connectfy/connectfy-notification-action-history-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
    restart: always
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
      - connectfy-api-gateway-network
      - connectfy-kafka-network
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production

  mongo:
    image: mongo:6.0
    container_name: connectfy-notification-action-history-mongo-prod
    volumes:
      - mongo-data:/data/db
    networks:
      - connectfy-notification-action-history-network
      - notifications-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: notificationsDb
    ports:
      - '25201:27017'

volumes:
  mongo-data:

networks:
  connectfy-notification-action-history-network:
    external: true
  notifications-db-network:
  connectfy-api-gateway-network:
    external: true
  connectfy-kafka-network:
    external: true
