export const MICROSERVICE_NAMES = {
  ACCOUNT: {
    TCP: 'ACCOUNT_SERVICE_TCP',
    KAFKA: 'ACCOUNT_SERVICE_KAFKA',
  },
  AUTH: {
    TCP: 'AUTH_SERVICE_TCP',
  },
  MESSENGER: {
    TCP: 'MESSENGER_SERVICE_TCP',
  },
  RELATIONSHIP: {
    TCP: 'RELATIONSHIP_SERVICE_TCP',
  },
  NOTIFICATION: {
    TCP: 'NOTIFICATION_SERVICE_TCP',
    KAFKA: 'NOTIFICATION_SERVICE_KAFKA',
  },
};

export const ENV = {
  CORE: {
    APP: {
      NODE_ENV: 'NODE_ENV',
      PORT: 'PORT',
    },
    DATABASE: {
      MONGO: {
        URI: 'MONGO_URI',
        DB_NAME: 'DB_NAME'
      },
    },
  },

  GATEWAY: {
    CLIENT_URL: 'CLIENT_URL',
    SESSION_SECRET: 'SESSION_SECRET_KEY',
  },

  AUTH: {
    JWT: {
      ACCESS: {
        SECRET: 'JWT_ACCESS_SECRET',
        EXPIRES_IN: 'JWT_ACCESS_EXPIRES_IN',
      },
      REFRESH: {
        SECRET: 'JWT_REFRESH_SECRET',
        EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
      },
      ACTIONS: {
        FORGOT_PASSWORD: 'FORGOT_PASSWORD_SECRET',
        CHANGE_EMAIL: 'CHANGE_EMAIL_SECRET',
        RESTORE_ACCOUNT: 'RESTORE_ACCOUNT_SECRET',
      },
    },

    KEYS: {
      FACE_DESCRIPTOR: 'FACE_DESCRIPTOR_KEY',
      USER_PRIVATE: 'USER_PRIVATE_KEY',
    },
  },

  OAUTH: {
    GOOGLE: {
      CLIENT_ID: 'GOOGLE_CLIENT_ID',
      CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET',
      CALLBACK_URL: 'GOOGLE_CALLBACK_URL',
      REDIRECT_URL: 'GOOGLE_CLIENT_REDIRECT_URL',
    },
  },

  NOTIFICATION: {
    EMAIL: {
      HOST: 'EMAIL_HOST',
      USER: 'EMAIL_USER',
      PASS: 'EMAIL_PASS',
    },
  },
};
